services:
  postgres:
    image: public.ecr.aws/bluegroundltd/postgis:17-3.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5438:5432"
