services:
  postgres:
    image: public.ecr.aws/docker/library/postgres:17.4-bullseye
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=mydb
    ports:
      - "5438:5432"
