[package]
name = "rustic-whole-table-transformator"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
rustic-transformator.workspace = true
rustic-base-transformations.workspace = true
