[package]
name = "rustic-result-validator"
version = "0.1.0"
edition = "2024"
license = "MIT"

[dependencies]
tracing.workspace = true
serde.workspace = true
toml.workspace = true
anyhow.workspace = true
colored.workspace = true
deadpool-postgres.workspace = true
bon.workspace = true
