on:
  workflow_call:

env:
  RUST_VERSION: 1.79.0

jobs:
  format-and-clippy:
    name: Cargo format & Clippy
    runs-on: arc-runner-set
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE }}
          aws-region: eu-west-1
      - name: Load CI_TOKEN
        uses: bluegroundltd/gha-tooling/get-ssm-parameter@main
        with:
          ssm-parameter-path: ${{ secrets.CI_TOKEN_PATH }}
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ env.JENKINS_GITHUB_TOKEN }}
      - uses: bluegroundltd/gha-tooling/setup-rust@main
        with:
          rust-version: ${{ env.RUST_VERSION }}
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Lint with Clippy
        run: cargo clippy --all
