name: Format & Clippy Pipeline

on:
  workflow_call:

env:
  RUST_VERSION: 1.85.0

permissions:
  contents: read

jobs:
  format-and-clippy:
    name: Cargo format & Clippy
    runs-on: arc-runner-set
    permissions:
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE }}
          aws-region: eu-west-1
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@559aa3035a47390ba96088dffa783b5d26da9326 # v1.1.1
      - name: Lint with Clippy
        run: cargo clippy --all
