name: Format & Clippy Pipeline

on:
  workflow_call:

env:
  RUST_VERSION: 1.80.0

jobs:
  format-and-clippy:
    name: Cargo format & Clippy
    runs-on: arc-runner-set
    permissions:
      id-token: write
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE }}
          aws-region: eu-west-1
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Rustfmt Check
        uses: actions-rust-lang/rustfmt@v1
      - name: Lint with Clippy
        run: cargo clippy --all
