name: Tests Pipeline

on:
  workflow_call:

env:
  RUST_VERSION: 1.85.0

permissions:
  contents: read

jobs:
  tests:
    name: Tests
    runs-on: arc-runner-set
    permissions:
      id-token: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@e3dd6a429d7300a6a4c196c26e071d42e0343502 # v4.0.2
        with:
          role-to-assume: ${{ secrets.CI_AWS_ROLE }}
          aws-region: eu-west-1
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: recursive
          token: ${{ secrets.CI_TOKEN }}
      - uses: actions-rust-lang/setup-rust-toolchain@9399c7bb15d4c7d47b27263d024f0a4978346ba4 # v1.11.0
        with:
          components: rustfmt, clippy
          toolchain: ${{ env.RUST_VERSION }}
      - name: Install cargo-nextest
        uses: baptiste0928/cargo-install@91c5da15570085bcde6f4d7aed98cb82d6769fd3 # v3.3.0
        with:
          crate: cargo-nextest
      - name: Run tests
        run: cargo nextest run --all
